name: 'Mondrian Policy Check'
description: 'Run Mondrian Zero Trust policy checks against your repository'
author: 'Chris McConnell'

inputs:
  rules:
    description: 'Comma-separated list of rule categories to run (iac,deploy,device)'
    required: false
    default: 'iac,deploy'
  fail-on-violations:
    description: 'Whether to fail the action if policy violations are found'
    required: false
    default: 'true'

outputs:
  violations-found:
    description: 'Number of policy violations found'
    value: ${{ steps.check.outputs.violations }}

runs:
  using: 'composite'
  steps:
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build Mondrian CLI
      shell: bash
      run: |
        echo "🔨 Building Mondrian CLI..."
        cd ${{ github.action_path }}/../../../
        go build -o mondrian cmd/mondrian/main.go
        chmod +x mondrian

    - name: Run Mondrian Policy Check
      id: check
      shell: bash
      run: |
        echo "🔍 Running Mondrian policy checks..."
        cd ${{ github.workspace }}
        
        # Run policy check
        mondrian_path="${{ github.action_path }}/../../../mondrian"
        $mondrian_path check
        check_result=$?
        
        # Set output
        if [ $check_result -eq 0 ]; then
          echo "violations=0" >> $GITHUB_OUTPUT
          echo "✅ All Mondrian policy checks passed!"
        else
          echo "violations=1" >> $GITHUB_OUTPUT
          echo "❌ Mondrian policy checks failed"
          
          if [ "${{ inputs.fail-on-violations }}" = "true" ]; then
            exit $check_result
          fi
        fi

branding:
  icon: 'shield'
  color: 'red'